"""Pure assembly of DDL text from catalog record dicts.

Ported from the lacanoid/pgddl extension (PostgreSQL licence): the clause
structure and per-column definition logic follow ddlx_describe and
ddlx_create_table, rewritten as client-side functions over plain dicts so
nothing is ever created in the observed database.  All identifiers and
literals arrive pre-quoted from the server (quote_ident/quote_literal in
the queries module); these functions only concatenate.

Intentionally out of scope (the output is for DBA reading, not restore):
ownership, ACLs, comments, row-level security policies, rules, per-column
storage/compression/statistics targets.
"""

from __future__ import annotations

from typing import Any

Record = dict[str, Any]

_PERSISTENCE_PREFIX = {"u": "UNLOGGED ", "t": "TEMPORARY "}
_CONSTRAINT_ORDER = {"p": 0, "u": 1, "x": 2, "f": 3, "c": 4}
_TRIGGER_ENABLE_CLAUSE = {
    "D": "DISABLE TRIGGER",
    "R": "ENABLE REPLICA TRIGGER",
    "A": "ENABLE ALWAYS TRIGGER",
}

# Clause keywords (longest first) that start a new indented line when found
# at parenthesis depth zero outside quotes; server deparse functions emit
# keywords in upper case, so matching is case-sensitive.
_INDEX_BREAKS = ("TABLESPACE", "INCLUDE", "WHERE", "WITH", "ON")
_CONSTRAINT_BREAKS = (
    "NOT DEFERRABLE",
    "NOT VALID",
    "REFERENCES",
    "DEFERRABLE",
    "INITIALLY",
    "ON UPDATE",
    "ON DELETE",
    "MATCH",
    "WHERE",
)
_TRIGGER_BREAKS = ("INSTEAD OF", "FOR EACH", "BEFORE", "EXECUTE", "AFTER", "WHEN")


def break_clauses(text: str, keywords: tuple[str, ...], indent: str) -> str:
    """Insert line breaks before clause keywords found at top level.

    Quoted strings/identifiers and anything inside parentheses are left
    untouched, so expressions and literals can never be split.
    """
    out: list[str] = []
    depth = 0
    quote: str | None = None
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if quote is not None:
            out.append(ch)
            if ch == quote:
                if i + 1 < n and text[i + 1] == quote:
                    out.append(text[i + 1])
                    i += 2
                    continue
                quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == " " and depth == 0:
            rest = text[i + 1 :]
            for keyword in keywords:
                after = rest[len(keyword) : len(keyword) + 1]
                if rest.startswith(keyword) and after in ("", " ", "("):
                    out.append("\n" + indent)
                    i += 1
                    break
            else:
                out.append(ch)
                i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def column_clause(col: Record) -> str:
    parts = [col["name_q"], " ", col["type_name"]]
    if col.get("fdw_options_sql"):
        parts.append(f" OPTIONS ({col['fdw_options_sql']})")
    if col.get("collation_sql"):
        parts.append(f" COLLATE {col['collation_sql']}")
    identity = col.get("identity") or ""
    generated = col.get("generated") or ""
    if col.get("not_null") and identity not in ("a", "d"):
        parts.append(" NOT NULL")
    if col.get("default_expr") and not identity and not generated:
        parts.append(f" DEFAULT {col['default_expr']}")
    if identity == "a":
        parts.append(" GENERATED ALWAYS AS IDENTITY")
    elif identity == "d":
        parts.append(" GENERATED BY DEFAULT AS IDENTITY")
    if generated == "s":
        parts.append(f" GENERATED ALWAYS AS ({col['default_expr']}) STORED")
    elif generated == "v":
        parts.append(f" GENERATED ALWAYS AS ({col['default_expr']}) VIRTUAL")
    return "".join(parts)


def table_constraint_clauses(constraints: list[Record]) -> list[Record]:
    kept = [
        c
        for c in constraints
        if c.get("is_local") and c.get("contype") in _CONSTRAINT_ORDER
    ]
    kept.sort(key=lambda c: (_CONSTRAINT_ORDER[c["contype"]], c["name_q"]))
    return kept


def create_table(rel: Record, columns: list[Record], constraints: list[Record]) -> str:
    name = rel["identifier"]
    keyword = "FOREIGN TABLE" if rel["relkind"] == "f" else "TABLE"
    prefix = _PERSISTENCE_PREFIX.get(rel.get("relpersistence") or "", "")
    local_constraints = table_constraint_clauses(constraints)

    head = f"CREATE {prefix}{keyword} {name}"
    deferred_constraints: list[Record] = []
    if rel.get("relispartition"):
        head += f"\n    PARTITION OF {rel['parents']}"
        if rel.get("partition_bound"):
            head += f"\n    {rel['partition_bound']}"
        deferred_constraints = local_constraints
    elif rel.get("of_type"):
        head += f"\n    OF {rel['of_type']}"
        deferred_constraints = local_constraints
    else:
        body = ["    " + column_clause(c) for c in columns if c.get("is_local")]
        body += [
            f"    CONSTRAINT {c['name_q']} "
            + break_clauses(c["definition"], _CONSTRAINT_BREAKS, " " * 8)
            for c in local_constraints
        ]
        head += " (\n" + ",\n".join(body) + "\n)" if body else " ()"

    tail: list[str] = []
    if rel.get("parents") and not rel.get("relispartition"):
        tail.append(f"INHERITS ({rel['parents']})")
    if rel.get("partition_key"):
        tail.append(f"PARTITION BY {rel['partition_key']}")
    access_method = rel.get("access_method")
    if access_method and access_method != "heap" and rel["relkind"] in ("r", "p"):
        tail.append(f"USING {access_method}")
    options = rel.get("reloptions") or ""
    if rel.get("relhasoids"):
        options = f"{options}, oids = true" if options else "oids = true"
    if options:
        tail.append(f"WITH ({options})")
    if rel.get("tablespace"):
        tail.append(f"TABLESPACE {rel['tablespace']}")
    if rel.get("foreign_server"):
        server = f"SERVER {rel['foreign_server']}"
        if rel.get("foreign_options_sql"):
            server += f" OPTIONS ({rel['foreign_options_sql']})"
        tail.append(server)

    text = "\n".join([head, *tail]) + ";"
    for c in deferred_constraints:
        definition = break_clauses(c["definition"], _CONSTRAINT_BREAKS, "    ")
        text += f"\nALTER TABLE {name}\n    ADD CONSTRAINT {c['name_q']} {definition};"
    return text


def create_view(rel: Record) -> str:
    options = f"\nWITH ({rel['reloptions']})" if rel.get("reloptions") else ""
    body = (rel.get("view_definition") or "").strip().rstrip(";")
    return f"CREATE OR REPLACE VIEW {rel['identifier']}{options} AS\n{body};"


def create_materialized_view(rel: Record) -> str:
    tail: list[str] = []
    access_method = rel.get("access_method")
    if access_method and access_method != "heap":
        tail.append(f"USING {access_method}")
    if rel.get("reloptions"):
        tail.append(f"WITH ({rel['reloptions']})")
    if rel.get("tablespace"):
        tail.append(f"TABLESPACE {rel['tablespace']}")
    clauses = "".join("\n" + part for part in tail)
    body = (rel.get("view_definition") or "").strip().rstrip(";")
    text = f"CREATE MATERIALIZED VIEW {rel['identifier']}{clauses} AS\n{body}"
    if not rel.get("relispopulated", True):
        text += "\n  WITH NO DATA"
    return text + ";"


def create_sequence(rel: Record, seq: Record) -> str:
    prefix = _PERSISTENCE_PREFIX.get(rel.get("relpersistence") or "", "")
    lines = [f"CREATE {prefix}SEQUENCE {rel['identifier']}"]
    if seq.get("data_type") and seq["data_type"] != "bigint":
        lines.append(f"    AS {seq['data_type']}")
    lines.append(f"    START WITH {seq['start_value']}")
    lines.append(f"    INCREMENT BY {seq['increment']}")
    lines.append(f"    MINVALUE {seq['min_value']}")
    lines.append(f"    MAXVALUE {seq['max_value']}")
    lines.append(f"    CACHE {seq['cache_size']}")
    if seq.get("cycle"):
        lines.append("    CYCLE")
    text = "\n".join(lines) + ";"
    if seq.get("owned_by"):
        text += f"\nALTER SEQUENCE {rel['identifier']} OWNED BY {seq['owned_by']};"
    return text


def create_index(rec: Record) -> str:
    text = break_clauses(rec["index_definition"], _INDEX_BREAKS, "    ") + ";"
    if rec.get("is_valid") is False:
        text += "\n-- WARNING: this index is marked INVALID"
    return text


def create_function(rec: Record) -> str:
    return rec["definition"].strip() + ";"


def create_trigger(rec: Record) -> str:
    text = break_clauses(rec["definition"].strip(), _TRIGGER_BREAKS, "    ") + ";"
    clause = _TRIGGER_ENABLE_CLAUSE.get(rec.get("enabled") or "")
    if clause:
        text += f"\nALTER TABLE {rec['table_identifier']} {clause} {rec['name_q']};"
    return text


def add_constraint(rec: Record) -> str:
    if rec.get("table_identifier"):
        target = f"ALTER TABLE {rec['table_identifier']}"
    else:
        target = f"ALTER DOMAIN {rec['domain_identifier']}"
    definition = break_clauses(rec["definition"], _CONSTRAINT_BREAKS, "    ")
    return f"{target}\n    ADD CONSTRAINT {rec['name_q']} {definition};"


def create_role(rec: Record) -> str:
    """CREATE ROLE without password material, plus memberships and settings."""
    options = []
    if rec.get("is_superuser"):
        options.append("SUPERUSER")
    if rec.get("create_db"):
        options.append("CREATEDB")
    if rec.get("create_role"):
        options.append("CREATEROLE")
    if rec.get("replication"):
        options.append("REPLICATION")
    if rec.get("bypass_rls"):
        options.append("BYPASSRLS")
    options.append("LOGIN" if rec.get("can_login") else "NOLOGIN")
    if rec.get("inherit") is False:
        options.append("NOINHERIT")
    if rec.get("connection_limit") is not None and rec["connection_limit"] >= 0:
        options.append(f"CONNECTION LIMIT {rec['connection_limit']}")
    if rec.get("valid_until"):
        options.append(f"VALID UNTIL '{rec['valid_until']}'")
    text = f"CREATE ROLE {rec['name_q']}\n    " + "\n    ".join(options) + ";"
    if rec.get("memberships_sql"):
        text += "\n" + rec["memberships_sql"]
    if rec.get("settings_sql"):
        text += "\n" + rec["settings_sql"]
    return text


_BUILTIN_TABLESPACE_NOTES = {
    "pg_default": (
        "-- pg_default is a built-in tablespace with no CREATE TABLESPACE statement.\n"
        "-- It maps to the base/ directory inside the cluster data directory."
    ),
    "pg_global": (
        "-- pg_global is a built-in tablespace with no CREATE TABLESPACE statement.\n"
        "-- It maps to the global/ directory and stores the shared catalogs."
    ),
}


def create_tablespace(rec: Record) -> str:
    if not rec.get("location"):
        text = _BUILTIN_TABLESPACE_NOTES.get(
            rec["identifier"],
            f"-- Tablespace {rec['identifier']} reports no location;"
            " no CREATE TABLESPACE statement is available.",
        )
    else:
        text = (
            f"CREATE TABLESPACE {rec['name_q']}\n"
            f"    LOCATION {_sql_literal(rec['location'])}"
        )
        if rec.get("options"):
            text += f"\n    WITH ({rec['options']})"
        text += ";"
    if rec.get("options") and not rec.get("location"):
        text += f"\nALTER TABLESPACE {rec['name_q']} SET ({rec['options']});"
    return text


def _sql_literal(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def create_database(rec: Record) -> str:
    lines = [f"CREATE DATABASE {rec['name_q']}"]
    lines.append(f"    WITH ENCODING '{rec['encoding']}'")
    if rec.get("lc_collate"):
        lines.append(f"    LC_COLLATE '{rec['lc_collate']}'")
    if rec.get("lc_ctype"):
        lines.append(f"    LC_CTYPE '{rec['lc_ctype']}'")
    if rec.get("locale_provider"):
        lines.append(f"    LOCALE_PROVIDER {rec['locale_provider']}")
    if rec.get("provider_locale"):
        lines.append(f"    ICU_LOCALE '{rec['provider_locale']}'")
    if rec.get("icu_rules"):
        lines.append(f"    ICU_RULES '{rec['icu_rules']}'")
    if rec.get("tablespace"):
        lines.append(f"    TABLESPACE {rec['tablespace']}")
    if rec.get("connection_limit") is not None and rec["connection_limit"] >= 0:
        lines.append(f"    CONNECTION LIMIT {rec['connection_limit']}")
    if rec.get("is_template"):
        lines.append("    IS_TEMPLATE true")
    if rec.get("allow_connections") is False:
        lines.append("    ALLOW_CONNECTIONS false")
    text = "\n".join(lines) + ";"
    if rec.get("settings_sql"):
        text += "\n" + rec["settings_sql"]
    return text


def create_enum_type(rec: Record) -> str:
    labels = rec.get("enum_labels") or ""
    return f"CREATE TYPE {rec['identifier']} AS ENUM (\n    {labels}\n);"


def create_domain(rec: Record, constraints: list[Record]) -> str:
    parts = [f"CREATE DOMAIN {rec['identifier']} AS {rec['domain_base']}"]
    if rec.get("domain_collation_sql"):
        parts.append(f"\n    COLLATE {rec['domain_collation_sql']}")
    if rec.get("domain_default"):
        parts.append(f"\n    DEFAULT {rec['domain_default']}")
    if rec.get("domain_not_null"):
        parts.append("\n    NOT NULL")
    checks = [c for c in constraints if c.get("contype") == "c"]
    for c in sorted(checks, key=lambda c: c["name_q"]):
        parts.append(f"\n    CONSTRAINT {c['name_q']} {c['definition']}")
    return "".join(parts) + ";"


def create_composite_type(rec: Record, columns: list[Record]) -> str:
    body = []
    for col in columns:
        clause = f"    {col['name_q']} {col['type_name']}"
        if col.get("collation_sql"):
            clause += f" COLLATE {col['collation_sql']}"
        body.append(clause)
    return f"CREATE TYPE {rec['identifier']} AS (\n" + ",\n".join(body) + "\n);"


def create_range_type(rec: Record) -> str:
    body = [f"    SUBTYPE = {rec['range_subtype']}"]
    if rec.get("range_subtype_opclass"):
        body.append(f"    SUBTYPE_OPCLASS = {rec['range_subtype_opclass']}")
    if rec.get("range_collation_sql"):
        body.append(f"    COLLATION = {rec['range_collation_sql']}")
    if rec.get("range_canonical"):
        body.append(f"    CANONICAL = {rec['range_canonical']}")
    if rec.get("range_subtype_diff"):
        body.append(f"    SUBTYPE_DIFF = {rec['range_subtype_diff']}")
    return f"CREATE TYPE {rec['identifier']} AS RANGE (\n" + ",\n".join(body) + "\n);"
